version: '3.8'

services:

  app:
    build:
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
      context: ./
      dockerfile: docker/app/Dockerfile
    container_name: studqr-app
    environment:
        XDEBUG_MODE: "${XDEBUG_MODE}"
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/app/supervisor/:/etc/supervisor/conf.d/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
        - "${APP_PORT}:80"
    networks:
      - studqr_net
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mysql:8.0.32
    container_name: studqr-db
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - studqr_db:/var/lib/mysql
    networks:
      - studqr_net

networks:
  studqr_net:
    driver: bridge

volumes:
    studqr_db:
        driver: local
